settings:
  application:
    host: 0.0.0.0
    mode: dev
    name: testApp
    port: "8000"
    readtimeout: 1
    writertimeout: 2
  database:
    dbtype: mysql
    host: mysql
    name: testApp
    port: 3306
    username: root
  jwt:
    secret: 8b9pkd5kyaVj0FtGuNIUunZl6zLmOAfbL1AeWBGwRjvhZ9PHU4etwoIlgdNFZpo4NMSj1j_FvFgRn5gEa433Ebuy35xwckNaKgv22sptIXC2Km
    timeout: 3600
  log:
    dir: temp/logs
