settings:
  application:
    host: 0.0.0.0
    mode: dev
    name: testApp
    port: "8000"
    readtimeout: 1
    writertimeout: 2
  database:
    dbtype: mysql
    host: localhost
    name: testApp
    port: 3306
    username: root
  jwt:
    secret: go-admin
    timeout: 3600
  log:
    dir: temp/logs
